#pragma config(Sensor, in1,    detectBallLeft, sensorAnalog)
#pragma config(Sensor, in2,    detectBallRight, sensorAnalog)
#pragma config(Sensor, in3,    opponentCheck,  sensorAnalog)
#pragma config(Sensor, in4,    storageCheck,   sensorAnalog)
#pragma config(Sensor, in5,    backTrackLeft,  sensorLineFollower)
#pragma config(Sensor, in6,    backTrackRight, sensorLineFollower)
#pragma config(Sensor, in7,    frontTrackLeft, sensorLineFollower)
#pragma config(Sensor, in8,    frontTrackRight, sensorLineFollower)
#pragma config(Sensor, dgtl1,  backLimitLeft,  sensorNone)
#pragma config(Sensor, dgtl2,  backLimitRight, sensorNone)
#pragma config(Sensor, dgtl3,  buttonStart,    sensorNone)
#pragma config(Sensor, dgtl4,  emergencyStop,  sensorNone)
#pragma config(Sensor, dgtl5,  encoderLeftInput, sensorQuadEncoder)
#pragma config(Sensor, dgtl7,  encoderRightInput, sensorQuadEncoder)
#pragma config(Sensor, dgtl9,  North,          sensorDigitalIn)
#pragma config(Sensor, dgtl10, South,          sensorDigitalIn)
#pragma config(Sensor, dgtl11, East,           sensorDigitalIn)
#pragma config(Sensor, dgtl12, West,           sensorDigitalIn)
#pragma config(Motor,  port2,           leftMotor,     tmotorVex393_MC29, openLoop, reversed, driveLeft)
#pragma config(Motor,  port3,           rightMotor,    tmotorVex393_MC29, openLoop, driveRight)
#pragma config(Motor,  port4,           catchSpinner,  tmotorServoContinuousRotation, openLoop, reversed)
#pragma config(Motor,  port5,           releaseSpinner, tmotorServoContinuousRotation, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// ==== Function Setup ==== //
void leaveStartingArea();
void searchBall();
void checkStorage();
void catchBall();
void releaseBall();
void boundaryDetection();
void obstacleDetection();
void obstacleAvoidance();
void depositBoxDetection();
float get_encoder_distance_cm(int raw_vex_encoder);
float get_line_distance_cm(int raw_vex_adc);
float get_sharp_distance_cm(int raw_vex_adc);
void movement(const char* direction);
void rotation(const char* direction);


// ==== Variable Setup ==== //
int cycle = 0;
float speedLeft = 0;
float speedRight = 0;
float speedControl = 1; //Controls power of the motors

// ==== PID Controller Variables ==== //
float FF=0.0,FFA=0.0001,Kp=0.00012629420,Ki=0.05,Kd=0,IMax=0.1;
float integral = 0.0;
float previous_error = 0.0,previous_setpoint = 0.0;
float dT = 0.02; // Assuming a fixed time step of 10ms for simplicity



task main(){

speedControl = 1;

while(true){


	//1000 = 5cm, 2000 = 10cm,
	if(SensorValue(detectBallLeft) > 2500){
		movement("bacsdfsdfk");
		delay(2000);
		//movement("stop");
	}
	else {
		movement("forward");
	}
	//leaveStartingArea();//Moves robot nearer to the ball area
	//delay(1000);
	//catchBall(); //Catches the ball
	//delay(500);
	//depositBoxDetection(); //Checks if the deposit box is detected
	//releaseBall(); //Releases the ball into the deposit box
	//delay(500);
	//searchBall();

//	cycle += 1;
	}
}

//Leave the Starting Area
void leaveStartingArea(){
	movement("forward");
	delay(1000);
}

//Searches for the ball
void searchBall(){
	int ballFound = 1;

	if (SensorValue(detectBallLeft) >= 2){
		ballFound = 0;
	}
}


//Checks if the ball is in the storage box
void checkStorage(){
	if (SensorValue(storageCheck) >= 2){
		//Ball is in storage
	}
	else{
		//Ball is not in storage
	}
}

//Catching Mechanism and Movement
void catchBall(){
	motor[catchSpinner] = 127;
	delay(1000);
	motor[catchSpinner] = 0;



}

//Release Mechanism and Movement
void releaseBall(){
	motor[catchSpinner] = -127;
	delay(1000);
	motor[catchSpinner] = 0;
}



//Boundary Detection
void boundaryDetection(){
	if (SensorValue(backTrackLeft) >= 2 || SensorValue(backTrackRight) >= 2){
		//Robot is at the boundary
	}
	else{
		//Robot is not at the boundary
	}
}

//Obstacle Detection
void obstacleDetection(){
	if (SensorValue(frontTrackLeft) >= 2 || SensorValue(frontTrackRight) >= 2){
		//Obstacle is detected
	}
	else{
		//Obstacle is not detected
	}
}

//Obstacle Avoidance
void obstacleAvoidance(){
	if (SensorValue(frontTrackLeft) >= 2 || SensorValue(frontTrackRight) >= 2){
		//Obstacle is detected
		movement("back");
		delay(1000);
		rotation("clockwise");
		delay(500);
		movement("forward");
	}
	else{
		//Obstacle is not detected
	}
}

//Deposit Box Alignment and Detection
void depositBoxDetection(){
	if (SensorValue(opponentCheck) >= 2){
		//Deposit box is detected
	}
	else{
		//Deposit box is not detected
	}
}

//Encoder Raw to Metric Conversion
float get_encoder_distance_cm(int raw_vex_encoder) {
	// Prevent divide-by-zero or negative results in case of stray low noise
	if (raw_vex_encoder <= 0) {
		return 0.0; // Out of range
	}

	// Assuming a specific conversion factor for the encoder
	float distance_cm = raw_vex_encoder * 0.1; // Example conversion factor

	return distance_cm;
}

//Line Sensor Analog to Metric Conversion
float get_line_distance_cm(int raw_vex_adc) {
	// Prevent divide-by-zero or negative results in case of stray low noise
	if (raw_vex_adc <= 100) {
		return 80.0; // Out of range
	}

	// 110000 / (ADC - 15) is calibrated specifically for 12-bit scaling
	float distance_cm = 110000.0 / (raw_vex_adc - 15.0);

	if (distance_cm < 10.0) distance_cm = 10.0;
	if (distance_cm > 80.0) distance_cm = 80.0;

	return distance_cm;
}


//Sharp Sensor Analogue to Metric Conversion
float get_sharp_distance_cm(int raw_vex_adc) {
    // Prevent divide-by-zero or negative results in case of stray low noise
    if (raw_vex_adc <= 100) {
        return 80.0; // Out of range
    }

    // 110000 / (ADC - 15) is calibrated specifically for 12-bit scaling
    float distance_cm = 110000.0 / (raw_vex_adc - 15.0);

    if (distance_cm < 10.0) distance_cm = 10.0;
    if (distance_cm > 80.0) distance_cm = 80.0;

    return distance_cm;
}

//Movement controls
void movement(const char* direction){
	speedControl = 0.6;
	if (strcmp(direction, "forward") == 0){
		speedLeft = 127*speedControl;
		speedRight = 127*speedControl;
		}
	else if (strcmp(direction, "back") == 0){
		speedLeft = -127*speedControl;
		speedRight = -127*speedControl;
		}
	else if (strcmp(direction, "left") == 0){
		speedLeft = 60*speedControl;
		speedRight = 127*speedControl;
		}
	else if (strcmp(direction, "right") == 0){
		speedLeft = 127*speedControl;
		speedRight = 60*speedControl;
		}
	else {
		speedLeft = speedRight = 0;
	}

	motor[leftMotor] = speedLeft;
	motor[rightMotor] = speedRight;
}

//Rotation Controls
void rotation(const char* direction){
	speedControl = 0.2;
	if (strcmp(direction, "clockwise") == 0){
		speedLeft = -127*speedControl;
		speedRight = 127*speedControl;
		}
	else if (strcmp(direction, "counter_clockwise") == 0){
		speedLeft = 127*speedControl;
		speedRight = -127*speedControl;
		}
	motor[leftMotor] = speedLeft;
	motor[rightMotor] = speedRight;
}

//PID Control
float pidControl(float setpoint, float measured_value) {
	// Calculate error
	float error = setpoint - measured_value;
	double changeSetpoint = (setpoint - previous_setpoint) / dT;

	// Proportional term
	float Pout = Kp * error;

	// Integral term
	integral += error;
	if (integral > IMax){
		integral = IMax;
	}
	else if (integral<-IMax){
		integral=-IMax;
	}
	float Iout = Ki * integral;

	// Derivative term
	float derivative = (error - previous_error)/dT;
	float Dout = Kd * derivative;

	// Calculate total output
	float output = Pout + Iout + Dout+FF*setpoint+FFA*changeSetpoint;

	// Save setpoint and error for next iteration
	previous_setpoint = setpoint;
	previous_error = error;

	return output;
}
