#pragma config(Sensor, in1,    detectBallLeft, sensorAnalog)
#pragma config(Sensor, in2,    detectBallRight, sensorAnalog)
#pragma config(Sensor, in3,    opponentCheck,  sensorAnalog)
#pragma config(Sensor, in4,    storageCheck,   sensorAnalog)
#pragma config(Sensor, in5,    backTrackLeft,  sensorLineFollower)
#pragma config(Sensor, in6,    backTrackRight, sensorLineFollower)
#pragma config(Sensor, in7,    frontTrackLeft, sensorLineFollower)
#pragma config(Sensor, in8,    frontTrackRight, sensorLineFollower)
#pragma config(Sensor, dgtl1,  digiCompass,    sensorDigitalIn)
#pragma config(Sensor, dgtl2,  backLimitLeft,  sensorNone)
#pragma config(Sensor, dgtl3,  backLimitRight, sensorNone)
#pragma config(Sensor, dgtl4,  limit1,         sensorNone)
#pragma config(Sensor, dgtl5,  limit2,         sensorNone)
#pragma config(Motor,  port1,           leftMotor,     tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           catchSpinner,  tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port3,           releaseSpinner, tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port10,          rightMotor,    tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// ==== Function Setup ==== //
void movement(const char* direction);
void rotation(const char* direction);
void searchBall();


// ==== Variable Setup ==== //
int cycle = 0;
int speedLeft = 0;
int speedRight = 0;
int speedControl = 1; //Controls power of the motors


task main(){


while(cycle >= 0){
	movement("forward");
	delay(1000);
	rotation("clockwise");
	delay(500);
	movement("stop");

	searchBall();

	}
}


//Searches for the ball
void searchBall(){
	int ballFound = 1;

	if (SensorValue(detectBallLeft) >= 2){
		ballFound = 0;
	}
}

//Catching Mechanism and Movement

//Release Mechanism and Movement

//Boundary Detection

//Deposit Box Alignment and Detection



//Movement controls
void movement(const char* direction){
	if (strcmp(direction, "forward") == 0){
		speedLeft = 127*speedControl;
		speedRight = 127*speedControl;
		}
	else if (strcmp(direction, "back") == 0){
		speedLeft = -127*speedControl;
		speedRight = -127*speedControl;
		}
	else if (strcmp(direction, "left") == 0){
		speedLeft = 60*speedControl;
		speedRight = 127*speedControl;
		}
	else if (strcmp(direction, "right") == 0){
		speedLeft = 127*speedControl;
		speedRight = 60*speedControl;
		}
	else {
		speedLeft = speedRight = 0;
	}

	motor[leftMotor] = speedLeft;
	motor[rightMotor] = speedRight;
}

//Rotation Controls
void rotation(const char* direction){
	if (strcmp(direction, "clockwise") == 0){
		speedLeft = 127*speedControl;
		speedRight = -127*speedControl;
		}
	else if (strcmp(direction, "counter_clockwise") == 0){
		speedLeft = -127*speedControl;
		speedRight = 127*speedControl;
		}
	motor[leftMotor] = speedLeft;
	motor[rightMotor] = speedRight;
}
