#pragma config(Motor,  port9,           servo1,        tmotorServoStandard, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
wait1Msec(500);
motor[servo1]=70;



}
