#pragma config(Sensor, in1,    sharp_1,        sensorAnalog)
#pragma config(Sensor, in2,    sharp_2,        sensorAnalog)
#pragma config(Sensor, in3,    sharp_3,        sensorAnalog)
#pragma config(Sensor, in4,    Analog_4,       sensorAnalog)
#pragma config(Sensor, in5,    Analog_5,       sensorAnalog)
#pragma config(Sensor, in6,    Analog_6,       sensorAnalog)
#pragma config(Sensor, in7,    Analog_7,       sensorAnalog)
#pragma config(Sensor, in8,    Analog_8,       sensorAnalog)
#pragma config(Sensor, dgtl1,  Digital_1,      sensorDigitalIn)
#pragma config(Sensor, dgtl2,  Digital_2,      sensorDigitalIn)
#pragma config(Sensor, dgtl3,  Digital_3,      sensorDigitalIn)
#pragma config(Sensor, dgtl4,  Digital_4,      sensorDigitalIn)
#pragma config(Sensor, dgtl5,  encoder_1,      sensorQuadEncoder)
#pragma config(Sensor, dgtl7,  encoder_2,      sensorQuadEncoder)
#pragma config(Sensor, dgtl9,  north,          sensorDigitalIn)
#pragma config(Sensor, dgtl10, east,           sensorDigitalIn)
#pragma config(Sensor, dgtl11, sourth,         sensorDigitalIn)
#pragma config(Sensor, dgtl12, west,           sensorDigitalIn)
#pragma config(Motor,  port2,           rightMotor,    tmotorServoContinuousRotation, openLoop, reversed)
#pragma config(Motor,  port3,           leftMotor,     tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port4,           MotorLeft393,  tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           MotorRight393, tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*----------------------------------------------------------------------------------------------------*\
|*                                        - Wait for Push 1 -                                         *|
|*                                      ROBOTC on VEX 2.0 CORTEX                                      *|
|*                                                                                                    *|
|*  This program instructs the robot to move forward at half speed until the bumper sensor is         *|
|*  pressed.  There is a two second pause at the beginning of the program.                            *|
|*                                                                                                    *|
|*                                        ROBOT CONFIGURATION                                         *|
|*    NOTES:                                                                                          *|
|*    1)  Reversing 'rightMotor' (port 2) in the "Motors and Sensors Setup" is needed with the        *|
|*        "Squarebot" mode, but may not be needed for all robot configurations.                       *|
|*                                                                                                    *|
|*    MOTORS & SENSORS:                                                                               *|
|*    [I/O Port]          [Name]              [Type]                [Description]                     *|
|*    Motor Port 2        rightMotor          VEX 3-wire module     Right side motor                  *|
|*    Motor Port 3        leftMotor           VEX 3-wire module     Left side motor                   *|
|*    Digital Port 6      touchSensor         VEX Bumper Switch     Front mounted, facing forward.    *|
\*-----------------------------------------------------------------------------------------------4246-*/


//+++++++++++++++++++++++++++++++++++++++++++++| MAIN |+++++++++++++++++++++++++++++++++++++++++++++++
task main()
{
	writeDebugStreamLine("IR sensor values: %d", SensorValue(Digital_1));
	writeDebugStreamLine("IR sensor values: %d", SensorValue(Analog_4));
	wait1Msec(2000);						            // Robot waits for 2000 milliseconds before executing program

	while(true)
	{
		while(SensorValue(sharp_1) > 1000)  // motor turning clockwise when distance sensor is activated
		{
			motor[rightMotor] = -127;			          // Motor on port2 is run at half (63) power reverse
			motor[leftMotor]  = -127;			          // Motor on port3 is run at half (63) power reverse
			motor[MotorLeft393]  = -127;			          	// Motor on port4 runs to the end  7 Aug 2023 Burhan
			motor[MotorRight393]  = -127;			          	// Motor on port4 runs to the end  7 Aug 2023 Burhan
			wait1Msec(2000);

			motor[rightMotor] = 0;			          // Motor on port2 is run at half (63) power reverse
			motor[leftMotor]  = 0;			          // Motor on port3 is run at half (63) power reverse
			motor[MotorLeft393]  = 0;			          		// Motor on port4 runs to the center 7 Aug 2023 Burhan
			motor[MotorRight393]  = 0;			          	// Motor on port4 runs to the end  7 Aug 2023 Burhan
			wait1Msec(2000);
		}

		while(SensorValue(Digital_2) == 0)		// motor turning counter clockwise when reflective sensor is activated
		{
			motor[rightMotor] = 127;			          // Motor on port2 is run at half (63) power forward
			motor[leftMotor]  = 127;			          // Motor on port3 is run at half (63) power forward
			motor[MotorLeft393]  = 127;			          	// Motor on port4 runs to the end 7 Aug 2023 Burhan
			motor[MotorRight393]  = 127;			          	// Motor on port4 runs to the end  7 Aug 2023 Burhan
			wait1Msec(2000);

			motor[rightMotor] = 0;			          // Motor on port2 is run at half (63) power reverse
			motor[leftMotor]  = 0;			          // Motor on port3 is run at half (63) power reverse
			motor[MotorLeft393]  = 0;			          		// Motor on port4 runs to the center 7 Aug 2023 Burhan
			motor[MotorRight393]  = 0;			          	// Motor on port4 runs to the end  7 Aug 2023 Burhan
			wait1Msec(2000);
		}
	}

}
//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
