#pragma config(Sensor, in1,    sharp1,         sensorAnalog)
#pragma config(Sensor, in2,    sharp2,         sensorAnalog)
#pragma config(Sensor, in3,    sharp3,         sensorAnalog)
#pragma config(Sensor, in4,    sharp4,         sensorAnalog)
#pragma config(Sensor, dgtl1,  reflective1,    sensorDigitalIn)
#pragma config(Sensor, dgtl2,  reflective2,    sensorDigitalIn)
#pragma config(Sensor, dgtl3,  reflective3,    sensorDigitalIn)
#pragma config(Sensor, dgtl4,  reflective4,    sensorDigitalIn)
#pragma config(Sensor, dgtl9,  north,          sensorDigitalIn)
#pragma config(Sensor, dgtl10, east,           sensorDigitalIn)
#pragma config(Sensor, dgtl11, sourth,         sensorDigitalIn)
#pragma config(Sensor, dgtl12, west,           sensorDigitalIn)
#pragma config(Motor,  port2,           Motor1,        tmotorServoContinuousRotation, openLoop, reversed)
#pragma config(Motor,  port3,           Servo1,        tmotorServoStandard, openLoop)
#pragma config(Motor,  port4,           leftMotor,     tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*----------------------------------------------------------------------------------------------------*\
|*                                        - Wait for Push 1 -                                         *|
|*                                      ROBOTC on VEX 2.0 CORTEX                                      *|
|*                                                                                                    *|
|*  This program instructs the robot to move forward at half speed until the bumper sensor is         *|
|*  pressed.  There is a two second pause at the beginning of the program.                            *|
|*                                                                                                    *|
|*                                        ROBOT CONFIGURATION                                         *|
|*    NOTES:                                                                                          *|
|*    1)  Reversing 'rightMotor' (port 2) in the "Motors and Sensors Setup" is needed with the        *|
|*        "Squarebot" mode, but may not be needed for all robot configurations.                       *|
|*                                                                                                    *|
|*    MOTORS & SENSORS:                                                                               *|
|*    [I/O Port]          [Name]              [Type]                [Description]                     *|
|*    Motor Port 2        rightMotor          VEX 3-wire module     Right side motor                  *|
|*    Motor Port 3        leftMotor           VEX 3-wire module     Left side motor                   *|
|*    Digital Port 6      touchSensor         VEX Bumper Switch     Front mounted, facing forward.    *|
\*-----------------------------------------------------------------------------------------------4246-*/


//+++++++++++++++++++++++++++++++++++++++++++++| MAIN |+++++++++++++++++++++++++++++++++++++++++++++++
task main()
{
	wait1Msec(2000);						            // Robot waits for 2000 milliseconds before executing program

		motor[Motor1] = -63;			          // Motor on port2 is run at half (63) power reverse
		motor(Servo1) = -255;
		motor[leftMotor]  = -63;			          // Motor on port3 is run at half (63) power reverse
		wait1Msec(3000);

		motor[Motor1] = 63;			          // Motor on port2 is run at half (63) power reverse
		motor(Servo1) = 255;
		motor[leftMotor]  = 63;			          // Motor on port3 is run at half (63) power reverse
		wait1Msec(3000);


		motor[Motor1] = 0;			          // Motor on port2 is run at half (63) power reverse
		motor(Servo1) = 0;
		motor[leftMotor]  = 0;			          // Motor on port3 is run at half (63) power reverse
		wait1Msec(2000);


}
//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
