#pragma config(Sensor, in1,    sharpSensor,    sensorAnalog)
#pragma config(Motor,  port2,           rightMotor,    tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port3,           servoMotor,    tmotorServoContinuousRotation, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma DebuggerWindows("Sensors")


//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*----------------------------------------------------------------------------------------------------*\
|*                                         - Moving Forward -                                         *|
|*                                      ROBOTC on VEX 2.0 CORTEX                                      *|
|*                                                                                                    *|
|*  This program instructs your robot to move forward at full power for three seconds.  There is a    *|
|*  two second pause at the beginning of the program.                                                 *|
|*                                                                                                    *|
|*                                        ROBOT CONFIGURATION                                         *|
|*    NOTES:                                                                                          *|
|*    1)  Reversing 'rightMotor' (port 2) in the "Motors and Sensors Setup" is needed with the        *|
|*        "Squarebot" mode, but may not be needed for all robot configurations.                       *|
|*    2)  Power levels that can be assigned to a motor port range from -127 (full reverse) to         *|
|*        127 (full forward).                                                                         *|
|*                                                                                                    *|
|*    MOTORS & SENSORS:                                                                               *|
|*    [I/O Port]          [Name]              [Type]                [Description]                     *|
|*    Motor Port 2        rightMotor          VEX 3-wire module     Right side motor                  *|
|*    Motor Port 3        leftMotor           VEX 3-wire module     Left side motor                   *|
\*-----------------------------------------------------------------------------------------------4246-*/


//+++++++++++++++++++++++++++++++++++++++++++++| MAIN |+++++++++++++++++++++++++++++++++++++++++++++++
task main()
{
	int threshold = 1000;

	wait1Msec(2000);						// Robot waits for 2000 milliseconds before executing program

	motor[rightMotor] = 200;		  // Motor on port2 is run at full (127) power forward

	while (true)
	{
		if(SensorValue(sharpSensor) < threshold)
 		{
 			motor[rightMotor] = 100;		  // Motor on port2 is run at full (127) power forward

			for(int i=-117; i<128; i+=10)     /* Starting 'i' at -117, and incrementing by 10, */
 			{                                 /* continue while 'i' is less than 0. */
  			motor[servoMotor] = i;          // Set 'servoMotor' to position 'i'.
  			wait1Msec(250);                 // Wait for 0.25 seconds (gives time for the servo to move)
   		}
		wait1Msec(3000);			        // Robot runs previous code for 3000 milliseconds before moving on
	}
	}									     // Program ends, and the robot stops
}
//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
