#pragma config(Sensor, dgtl5,  encoderA,       sensorQuadEncoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	SensorValue[encoderA]=0;

	while(true) {
		int counts = SensorValue[encoderA];
		float angle = (counts / 360.0)*360;





		wait1Msec(100);

		writeDebugStreamLine("%f",angle);
	}


}
