#pragma config(Sensor, dgtl1,  RefSensor1,     sensorDigitalIn)
#pragma config(Sensor, dgtl12, RefSensor2,     sensorDigitalIn)
#pragma config(Motor,  port2,           Motor1,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           Servo1,        tmotorServoStandard, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*----------------------------------------------------------------------------------------------------*\
|*                                        - Wait for Push 1 -                                         *|
|*                                      ROBOTC on VEX 2.0 CORTEX                                      *|
|*                                                                                                    *|
|*  This program instructs the robot to move forward at half speed until the bumper sensor is         *|
|*  pressed.  There is a two second pause at the beginning of the program.                            *|
|*                                                                                                    *|
|*                                        ROBOT CONFIGURATION                                         *|
|*    NOTES:                                                                                          *|
|*    1)  Reversing 'rightMotor' (port 2) in the "Motors and Sensors Setup" is needed with the        *|
|*        "Squarebot" mode, but may not be needed for all robot configurations.                       *|
|*                                                                                                    *|
|*    MOTORS & SENSORS:                                                                               *|
|*    [I/O Port]          [Name]              [Type]                [Description]                     *|
|*    Motor Port 2        rightMotor          VEX 3-wire module     Right side motor                  *|
|*    Motor Port 3        leftMotor           VEX 3-wire module     Left side motor                   *|
|*    Digital Port 6      touchSensor         VEX Bumper Switch     Front mounted, facing forward.    *|
\*-----------------------------------------------------------------------------------------------4246-*/


//+++++++++++++++++++++++++++++++++++++++++++++| MAIN |+++++++++++++++++++++++++++++++++++++++++++++++
task main()
{
	while(true)
	{
	wait1Msec(2000);						      // Robot waits for 2000 milliseconds before executing program

	motor[Motor1] = 63;			          // Motor on port2 is run at half (63) power forward

	motor[Servo1] = -127;       	// Set 'servoMotor' to position -127 (negative end of range)
    wait1Msec(500);                 // Wait for 0.5 seconds (gives time for the servo to move)



	while(SensorValue(RefSensor1) == 0)		// Loop while robot's bumper/touch sensor isn't pressed in
	{
		motor[Motor1] = -63;			          // Motor on port2 is run at half (63) power reverse

		for(int i=-117; i<128; i+=10)     /* Starting 'i' at -117, and incrementing by 10, */
    {                                 /* continue while 'i' is less than 0. */
      motor[Servo1] = i;          // Set 'servoMotor' to position 'i'.
      wait1Msec(250);                 // Wait for 0.25 seconds (gives time for the servo to move)motor[Servo1] = 127;							// Servo on port3 Set to position 127 (positive end of range)
		}
	}
	}
}
//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
